language: node_js
node_js:
  - 8
cache: npm
services:
  - docker
script:
  - cd ./FlexFileUpload/
  - npm install
  - npm install -g kinvey-cli@5.0.0-alpha.0
  - KINVEY_USER_2FA_TOKEN=$(docker run --rm gzm55/oathtool --totp -b $KINVEY_USER_2FA_SECRET)
  - kinvey profile create testProfile --email $KINVEY_USER_EMAIL --password $KINVEY_USER_PASSWORD --2fa $KINVEY_USER_2FA_TOKEN
