language: node_js
node_js:
  - 8
cache: npm
services:
  - docker
script:
  - cd ./FlexFileUpload/
  - npm install
  - npm install -g kinvey-cli@5.0.0-alpha.0
  - export KINVEY_APP_NAME="MyProgressAppy"
  - export KINVEY_APP_ENV_NAME="test"
  - export KINVEY_SERVICE_ENV_NAME="test"
  - export KINVEY_SERVICE_ID="44630668c22e41289d2212897b5117e5"
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export KINVEY_CLI_2FA=$(docker run --rm gzm55/oathtool --totp -b $KINVEY_USER_2FA_SECRET)
  - kinvey profile create "testProfile"
  - kinvey appenv create ${KINVEY_APP_ENV_NAME} --app ${KINVEY_APP_NAME} test.json
  - kinvey flex deploy
  - ./awaitDeployEnd.sh
