services:
  - docker
before_script:
  - docker build -t matioa/flex-file-upload .
  - docker run --name sharkasm matioa/flex-file-upload
script:
  - docker exec sharkasm npm run test
after_script:
  - docker stop sharkasm
branches:
  only:
    - master
