language: node_js
node_js:
  - 8
cache: npm
services:
  - docker
before_install:
  - cd ./FlexFileUpload/
install:
  - apt-get install grep awk
  - npm install
  - npm install -g kinvey-cli@5.0.0-alpha.0
script:
  - export KINVEY_APP_NAME="MyProgressApp"
  - export KINVEY_APP_ENV_NAME="test"
  - export KINVEY_SERVICE_ENV_NAME="test"
  - export KINVEY_SERVICE_ID="44630668c22e41289d2212897b5117e5"
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export KINVEY_USER_2FA_TOKEN=$(docker run --rm gzm55/oathtool --totp -b $KINVEY_USER_2FA_SECRET)
  - kinvey profile create "testProfile" --2fa ${KINVEY_USER_2FA_TOKEN}
  - kinvey appenv create ${KINVEY_APP_ENV_NAME} --app ${KINVEY_APP_NAME} ../test.json
  - kinvey flex deploy --service ${KINVEY_SERVICE_ID} --env ${KINVEY_SERVICE_ENV_NAME}
  - ../awaitDeployEnd.sh
